# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../ui/main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1920, 1080)
        mainWindow.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 40))
        self.labelTitle.setStyleSheet("font: 87 25pt \"Noto Sans KR\";\n"
"color: rgb(0, 0, 0);")
        self.labelTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelTitle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelTitle.setObjectName("labelTitle")
        self.mainLayout.addWidget(self.labelTitle, 0, 1, 2, 1)
        self.labelTime = QtWidgets.QLabel(self.centralwidget)
        self.labelTime.setMinimumSize(QtCore.QSize(0, 20))
        self.labelTime.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"Noto Sans KR\";")
        self.labelTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTime.setObjectName("labelTime")
        self.mainLayout.addWidget(self.labelTime, 1, 2, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setMinimumSize(QtCore.QSize(0, 20))
        self.labelDate.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"Noto Sans KR\";")
        self.labelDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDate.setObjectName("labelDate")
        self.mainLayout.addWidget(self.labelDate, 0, 2, 1, 1)
        self.labelHome = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHome.sizePolicy().hasHeightForWidth())
        self.labelHome.setSizePolicy(sizePolicy)
        self.labelHome.setMinimumSize(QtCore.QSize(60, 60))
        self.labelHome.setMaximumSize(QtCore.QSize(60, 60))
        self.labelHome.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 9pt \"Noto Sans KR\";")
        self.labelHome.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelHome.setObjectName("labelHome")
        self.mainLayout.addWidget(self.labelHome, 0, 0, 2, 1)
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName("mainWidget")
        self.mainLayout.addWidget(self.mainWidget, 2, 0, 1, 3)
        self.horizontalLayout.addLayout(self.mainLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("mainWindow", "가게 이름"))
        self.labelTime.setText(_translate("mainWindow", "오전 10:00"))
        self.labelDate.setText(_translate("mainWindow", "2021-02-02"))
        self.labelHome.setText(_translate("mainWindow", "Home"))
